

#MYSQL_HOST: 127.0.0.1
mybatis-plus:
  mapper-locations: classpath*:com/demo/mettingfilm/**/xml/*Mapper.xml
  global-config:
    #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    id-type: 0
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.107.97.4}:${MYSQL_PORT:3306}/${MYSQL_NAME:demo}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:236675}
    filters: log4j,wall,mergeStat
    driverClassName: com.mysql.jdbc.Driver


logging:
  config: classpath:logback.xml

#解决lombok警告
config:
  stopBubbling: true
lombok:
  equalsAndHashCode:
    callSuper: call



