
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    basedir: /tmp/tomcat
    connection-timeout: 60000

spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        - id: demo-client
          #uri: http://localhost:8101
          uri: lb://demo-client
          predicates:
            - Path=/consumer/consumer/**
          #路由的id，没有固定规则，建议配合服务名使用
        - id: demo-user
          #提供服务的路由地址
          #uri: http://localhost:8100
          uri: lb://demo-user
          #断言，路径相匹配就进行路由
          predicates:
            - Path=/user/user/**


eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:8761/eureka/


