
#MYSQL_HOST: 127.0.0.1
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    id-type: 0
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:47.107.97.4}:${MYSQL_PORT:3306}/${MYSQL_NAME:demo}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:236675}
    filters: log4j,wall,mergeStat
    driverClassName: com.mysql.jdbc.Driver

## ribbon配置服务名称 Service-ID
#demo-user:
#  ribbon:
#    # 属性配置方式【推荐】配置文件配置负载均衡算法-我这里使用的是自定义的Ribbon的负载均衡算法，默认
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    #开启hystrix
    enabled: true
    #feign之http性能优化
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true
      # 配置压缩支持的MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小下限
      min-request-size: 2048
      # 配置响应GZIP压缩
    response:
      enabled: true

logging:
  config: classpath:logback.xml
